List<Map<String, dynamic>> Edison_Division = [
  {'team_number': '130', 'team_name': 'Blazing Spirits', 'from': 'Windsor, CT, USA'} ,
  {'team_number': '3050', 'team_name': 'G-Bots', 'from': 'Las Vegas, NV, USA'} ,
  {'team_number': '3825', 'team_name': 'Ψ Lynx', 'from': 'Anchorage, AK, USA'} ,
  {'team_number': '4848', 'team_name': 'Chaos', 'from': 'Laredo, TX, USA'} ,
  {'team_number': '5741', 'team_name': 'RoboHawks Red', 'from': 'Hinesburg, VT, USA'} ,
  {'team_number': '6134', 'team_name': 'Black Frogs', 'from': 'Novi, MI, USA'} ,
  {'team_number': '6448', 'team_name': 'Blue Jays', 'from': 'New Orleans, LA, USA'} ,
  {'team_number': '7842', 'team_name': 'Browncoats', 'from': 'Huntsville, AL, USA'} ,
  {'team_number': '9848', 'team_name': 'GearView', 'from': 'Mullica Hill, NJ, USA'} ,
  {'team_number': '9864', 'team_name': 'Jug Rox Robotix', 'from': 'Shoals, IN, USA'} ,
  {'team_number': '10136', 'team_name': 'Frost RoboFalcons', 'from': 'Livonia, MI, USA'} ,
  {'team_number': '10644', 'team_name': 'CyBugs', 'from': 'Saline, MI, USA'} ,
  {'team_number': '11329', 'team_name': 'I.C.E. Robotics', 'from': 'Bloomington, IN, USA'} ,
  {'team_number': '12611', 'team_name': 'TechNova', 'from': 'Brentwood, TN, USA'} ,
  {'team_number': '12808', 'team_name': 'RevAmped Robotics', 'from': 'Portland, OR, USA'} ,
  {'team_number': '12887', 'team_name': 'Devolt Phobos', 'from': 'Chihuahua, CHH, Mexico'} ,
  {'team_number': '12993', 'team_name': 'RoboKings Aurum', 'from': 'Sunshine Coast, QLD, Australia'} ,
  {'team_number': '13201', 'team_name': 'Team Hazmat', 'from': 'Brookfield, WI, USA'} ,
  {'team_number': '14343', 'team_name': 'Escape Velocity', 'from': 'Bellevue, WA, USA'} ,
  {'team_number': '14380', 'team_name': 'Blue BotBuilders', 'from': 'Northgate, QLD, Australia'} ,
  {'team_number': '14712', 'team_name': 'Ruckus Robotics', 'from': 'New York, NY, USA'} ,
  {'team_number': '15167', 'team_name': 'Robo Troopers', 'from': 'Herndon, VA, USA'} ,
  {'team_number': '15534', 'team_name': 'VERTEX', 'from': 'Exeter, NH, USA'} ,
  {'team_number': '15972', 'team_name': 'TehnoZ', 'from': 'Pitesti, AG, Romania'} ,
  {'team_number': '16498', 'team_name': 'Plus Gang', 'from': 'Ballwin, MO, USA'} ,
  {'team_number': '17257', 'team_name': 'GoBuilder.GC', 'from': 'Douliu, YUN, Chinese Taipei'} ,
  {'team_number': '17955', 'team_name': 'Astrovo', 'from': 'Cape Town, WC, South Africa'} ,
  {'team_number': '17969', 'team_name': 'MECH', 'from': 'Denver, CO, USA'} ,
  {'team_number': '18011', 'team_name': 'Hyperion Bots', 'from': 'Cape Town, WC, South Africa'} ,
  {'team_number': '18030', 'team_name': 'ViperBots Leviathan', 'from': 'Austin, TX, USA'} ,
  {'team_number': '18140', 'team_name': 'TBD (ThunderBolts in Disguise)', 'from': 'Friendswood, TX, USA'} ,
  {'team_number': '18422', 'team_name': 'LYBOTICS Wizards Team', 'from': 'Tripoli, TB, Libya'} ,
  {'team_number': '18603', 'team_name': 'TeraBridges', 'from': 'Pittsburgh, PA, USA'} ,
  {'team_number': '18840', 'team_name': 'Reynolds Reybots', 'from': 'Victoria, BC, Canada'} ,
  {'team_number': '19164', 'team_name': 'Cristabol', 'from': 'Almaty, ALA, Kazakhstan'} ,
  {'team_number': '19213', 'team_name': 'Mystery', 'from': 'Tainan, TNN, Chinese Taipei'} ,
  {'team_number': '19294', 'team_name': 'LYBOTICS Super Nova Team', 'from': 'Benghazi, BA, Libya'} ,
  {'team_number': '19666', 'team_name': 'Forever Knight', 'from': 'Shanghai, SH, China'} ,
  {'team_number': '19743', 'team_name': 'Definitely Human', 'from': 'La Jolla, CA, USA'} ,
  {'team_number': '19862', 'team_name': 'Mecha Mantises', 'from': 'Fremont, CA, USA'} ,
  {'team_number': '20278', 'team_name': 'Neurobots #1', 'from': 'LAssomption, QC, Canada'} ,
  {'team_number': '20506', 'team_name': 'Foshay Learning Center 2', 'from': 'Los Angeles, CA, USA'} ,
  {'team_number': '20744', 'team_name': '24 Karat', 'from': 'Kent, OH, USA'} ,
  {'team_number': '20871', 'team_name': 'Eureka', 'from': 'Mumbai, MH, India'} ,
  {'team_number': '21418', 'team_name': 'SeaCow Robotics', 'from': 'Benton, AR, USA'} ,
  {'team_number': '22077', 'team_name': 'Marcus Minions', 'from': 'Flower Mound, TX, USA'} ,
  {'team_number': '23112', 'team_name': 'Laffan', 'from': 'Doha, DA, Qatar'} ,
  {'team_number': '23160', 'team_name': 'Redshift', 'from': 'Butterworth, 07, Malaysia'} ,
  {'team_number': '23521', 'team_name': 'DeSoto Technix', 'from': 'Olive Branch, MS, USA'} ,
  {'team_number': '23550', 'team_name': 'Robot 11 Janvier', 'from': 'Fes, MOU, Morocco'} ,
  {'team_number': '24033', 'team_name': 'Alphatronic', 'from': 'Cluj-Napoca, CJ, Romania'} ,
  {'team_number': '24064', 'team_name': 'ITKAN JIAR Janktastrophe', 'from': 'Durham, NC, USA'} ,
  {'team_number': '24230', 'team_name': 'Junior AG Robotik', 'from': 'büyükçekmece, 34, Türkiye'} ,
  {'team_number': '24697', 'team_name': 'SANA', 'from': 'Almaty, ALA, Kazakhstan'} ,
  {'team_number': '24751', 'team_name': 'GreenAms Robotics Team', 'from': 'Hanoi, HN, Vietnam'} ,
  {'team_number': '24906', 'team_name': 'TC', 'from': 'Osan-si, 41, South Korea'} ,
  {'team_number': '25218', 'team_name': 'ElephantTech', 'from': 'Shanghai, SH, China'} ,
  {'team_number': '25324', 'team_name': 'RBS2', 'from': 'Osan, 41, South Korea'} ,
  {'team_number': '25609', 'team_name': 'LOAD Robotics', 'from': 'Odessa, DE, USA'} ,
  {'team_number': '25631', 'team_name': 'Proxima Nova', 'from': 'Lake Oswego, OR, USA'} ,
  {'team_number': '26398', 'team_name': 'Red Wing Robotics', 'from': 'Chattanooga, TN, USA'} ,
  {'team_number': '26857', 'team_name': 'Sweet Mysteries', 'from': 'Broken Arrow, OK, USA'} ,
  {'team_number': '26914', 'team_name': 'ROBOTECH FTC', 'from': 'Aracaju, SE, Brazil'} ,
  {'team_number': '28349', 'team_name': 'The Revolutionaries', 'from': 'Abuja, FC, Nigeria'}
];

List<Map<String, dynamic>> Franklin_Division = [
  {'team_number': '252', 'team_name': 'Electric Quahogs', 'from': 'Providence, RI, USA'} ,
  {'team_number': '772', 'team_name': 'Golden Dragons', 'from': 'Hartsville, SC, USA'} ,
  {'team_number': '3747', 'team_name': 'The Hive', 'from': 'Sandy, UT, USA'} ,
  {'team_number': '4133', 'team_name': 'Fusion', 'from': 'Helena, MT, USA'} ,
  {'team_number': '5064', 'team_name': 'Aperture Science', 'from': 'Morganton, NC, USA'} ,
  {'team_number': '5470', 'team_name': 'Rambotics', 'from': 'El Paso, TX, USA'} ,
  {'team_number': '6988', 'team_name': 'CyberStingers Gold', 'from': 'Thomasville, GA, USA'} ,
  {'team_number': '7034', 'team_name': 'Singularity Technology 7034', 'from': 'Wilton, CT, USA'} ,
  {'team_number': '7172', 'team_name': 'Technical Difficulties', 'from': 'Plano, TX, USA'} ,
  {'team_number': '7242', 'team_name': 'BC Robocats', 'from': 'Bridge Creek, OK, USA'} ,
  {'team_number': '7477', 'team_name': 'Super 7', 'from': 'Oviedo, FL, USA'} ,
  {'team_number': '8417', 'team_name': "'Lectric Legends", 'from': 'Winchester, KY, USA'} ,
  {'team_number': '10091', 'team_name': 'N.Y.A.N. Robotics - Not Your Average Nerds', 'from': 'Mundelein, IL, USA'} ,
  {'team_number': '10265', 'team_name': 'Force Green', 'from': 'Ballwin, MO, USA'} ,
  {'team_number': '10435', 'team_name': 'Circuit Breakers', 'from': 'Waukee, IA, USA'} ,
  {'team_number': '10544', 'team_name': 'Cyber Eagles', 'from': 'Sherwood Park, AB, Canada'} ,
  {'team_number': '11511', 'team_name': 'Referees', 'from': 'Auckland, AUK, New Zealand'} ,
  {'team_number': '12014', 'team_name': 'FireWires', 'from': 'Osceola, IN, USA'} ,
  {'team_number': '12016', 'team_name': 'MISHMASH', 'from': 'Beer Sheva, D, Israel'} ,
  {'team_number': '12524', 'team_name': 'Sputnik Original', 'from': 'Independent'} ,
  {'team_number': '12635', 'team_name': 'Kuriosity Robotics', 'from': 'Palo Alto, CA, USA'} ,
  {'team_number': '14295', 'team_name': 'Operation T.A.C.', 'from': 'San Juan Capistrano, CA, USA'} ,
  {'team_number': '14825', 'team_name': 'Team Waffles', 'from': 'Honolulu, HI, USA'} ,
  {'team_number': '14872', 'team_name': 'Orbit Knights', 'from': 'Binyamina, HA, Israel'} ,
  {'team_number': '14903', 'team_name': 'SharkBots', 'from': 'Mamaroneck, NY, USA'} ,
  {'team_number': '15104', 'team_name': 'Static Eagles', 'from': 'Hartland, MI, USA'} ,
  {'team_number': '15298', 'team_name': 'RoboTen', 'from': 'peqiin, Z, Israel'} ,
  {'team_number': '15527', 'team_name': 'Ramstein HS (Team 3)', 'from': 'APO, AE, USA'} ,
  {'team_number': '16205', 'team_name': 'Lightning Bots', 'from': 'Coquitlam, BC, Canada'} ,
  {'team_number': '16265', 'team_name': 'ENIGMA', 'from': 'Albuquerque, NM, USA'} ,
  {'team_number': '16413', 'team_name': 'Lo-Ellen Robotics', 'from': 'Sudbury, ON, Canada'} ,
  {'team_number': '17315', 'team_name': 'Tomahawk', 'from': 'Austin, TX, USA'} ,
  {'team_number': '17483', 'team_name': 'Blackout', 'from': 'Broomfield, CO, USA'} ,
  {'team_number': '17861', 'team_name': 'CSH', 'from': 'Timisoara, TM, Romania'} ,
  {'team_number': '17980', 'team_name': 'AISK Hurricane', 'from': 'Kingston 6, 02, Jamaica'} ,
  {'team_number': '18139', 'team_name': 'Rebel Robotics', 'from': 'Norfolk, NE, USA'} ,
  {'team_number': '18225', 'team_name': 'High Definition', 'from': 'Bellevue, WA, USA'} ,
  {'team_number': '18438', 'team_name': 'Wolfpack Machina', 'from': 'Beverly, MA, USA'} ,
  {'team_number': '19098', 'team_name': 'Eastern Foxes', 'from': 'Ploiesti, PH, Romania'} ,
  {'team_number': '19411', 'team_name': 'Tech Tigers', 'from': 'Sharon, MA, USA'} ,
  {'team_number': '20332', 'team_name': 'Just Add Logic', 'from': 'Troy, MI, USA'} ,
  {'team_number': '20515', 'team_name': 'Cubed ETs', 'from': 'Taylorsville, UT, USA'} ,
  {'team_number': '21229', 'team_name': 'Quality Control', 'from': 'Bellevue, WA, USA'} ,
  {'team_number': '21575', 'team_name': 'Go2STEAM', 'from': 'Sleman, YO, Indonesia'} ,
  {'team_number': '22168', 'team_name': 'Capybearings', 'from': 'Junction City, OR, USA'} ,
  {'team_number': '22795', 'team_name': 'NZ Blackbots', 'from': 'Hastings, HKB, New Zealand'} ,
  {'team_number': '22858', 'team_name': 'Flying Sausers', 'from': 'Cincinnati, OH, USA'} ,
  {'team_number': '23014', 'team_name': 'The Flying Dutchman', 'from': 'Wassenaar, ZH, Netherlands'} ,
  {'team_number': '23207', 'team_name': 'LEGO my Eggo Robotics', 'from': 'Meridian, ID, USA'} ,
  {'team_number': '23251', 'team_name': 'Triple Fault', 'from': 'San Diego, CA, USA'} ,
  {'team_number': '23268', 'team_name': 'Ultraviolet', 'from': 'Hackettstown, NJ, USA'} ,
  {'team_number': '23435', 'team_name': 'Gyrobotic Droids', 'from': 'West Chester, OH, USA'} ,
  {'team_number': '23974', 'team_name': 'A.S.T.R.O. Vikings', 'from': 'Alamogordo, NM, USA'} ,
  {'team_number': '24070', 'team_name': 'AllNew101', 'from': 'Muang, 52, Thailand'} ,
  {'team_number': '24461', 'team_name': 'Automates', 'from': 'Rouyn-Noranda, QC, Canada'} ,
  {'team_number': '24670', 'team_name': 'PID', 'from': 'Almaty, ALA, Kazakhstan'} ,
  {'team_number': '25153', 'team_name': 'Cartesian Robotics', 'from': 'Çankaya, 06, Türkiye'} ,
  {'team_number': '25242', 'team_name': 'Rise And Shine', 'from': 'Ha Noi, HN, Vietnam'} ,
  {'team_number': '25316', 'team_name': 'Eagles', 'from': 'Yeongju-Si, 47, South Korea'} ,
  {'team_number': '25353', 'team_name': 'The ISLC Robolutionaries', 'from': 'South Gate, CA, USA'} ,
  {'team_number': '26000', 'team_name': 'Theseus', 'from': 'Brisbane, QLD, Australia'} ,
  {'team_number': '26193', 'team_name': 'Rival Robotics', 'from': 'Davenport, ND, USA'} ,
  {'team_number': '27772', 'team_name': 'JelToqSun', 'from': 'Karaganda, KAR, Kazakhstan'} ,
  {'team_number': '29208', 'team_name': 'kams sdra', 'from': 'tabuk, 07, Saudi Arabia'}
];

List<Map<String, dynamic>> Jemison_Division = [
  {'team_number': '369', 'team_name': 'Oakton Cougar Robotics 369', 'from': 'Vienna, VA, USA'} ,
  {'team_number': '701', 'team_name': 'The GONK Squad', 'from': 'North Kingstown, RI, USA'} ,
  {'team_number': '3188', 'team_name': 'Squiggle Splat Bang', 'from': 'Powell, WY, USA'} ,
  {'team_number': '3189', 'team_name': 'Rapid Unscheduled Disassembly', 'from': 'Powell, WY, USA'} ,
  {'team_number': '3977', 'team_name': 'Stanislas Tech Team', 'from': 'Delft, ZH, Netherlands'} ,
  {'team_number': '4017', 'team_name': 'RoboPandas', 'from': 'Floral Park, NY, USA'} ,
  {'team_number': '4348', 'team_name': 'RoboKnights', 'from': 'Sherman Oaks , CA, USA'} ,
  {'team_number': '4410', 'team_name': 'ARC Lightning', 'from': 'Andover, MA, USA'} ,
  {'team_number': '5026', 'team_name': 'Tesla Coils', 'from': 'Kimberly, ID, USA'} ,
  {'team_number': '5979', 'team_name': 'CyberStingers Blue', 'from': 'Thomasville, GA, USA'} ,
  {'team_number': '6165', 'team_name': 'MSET CuttleFish', 'from': 'Saratoga, CA, USA'} ,
  {'team_number': '6294', 'team_name': 'Atomic Toads', 'from': 'Novi, MI, USA'} ,
  {'team_number': '6582', 'team_name': 'Kaiserslautern HS - Raider Robotics', 'from': 'APO, AE, USA'} ,
  {'team_number': '6962', 'team_name': 'Pokébolts', 'from': 'Honolulu, HI, USA'} ,
  {'team_number': '7244', 'team_name': 'OUT of the BOX Robotics', 'from': 'Thorndale, PA, USA'} ,
  {'team_number': '8617', 'team_name': 'Techno Tigers', 'from': 'Melbourne, FL, USA'} ,
  {'team_number': '8680', 'team_name': 'Kraken-Pinion', 'from': 'Mequon, WI, USA'} ,
  {'team_number': '9879', 'team_name': 'Root Negative One', 'from': 'Springdale, AR, USA'} ,
  {'team_number': '10015', 'team_name': 'Hyper Droid', 'from': 'Calgary, AB, Canada'} ,
  {'team_number': '10255', 'team_name': 'RoboDux', 'from': 'Zeeland, MI, USA'} ,
  {'team_number': '10298', 'team_name': 'Brain Stormz', 'from': 'Newbury Park, CA, USA'} ,
  {'team_number': '10355', 'team_name': 'Project Peacock', 'from': 'Tulsa, OK, USA'} ,
  {'team_number': '10392', 'team_name': 'The Rolling Drones', 'from': 'Brooklyn, NY, USA'} ,
  {'team_number': '11146', 'team_name': 'Barker Redbacks', 'from': 'Hornsby, NSW, Australia'} ,
  {'team_number': '11770', 'team_name': 'Curiosity', 'from': 'Los Angeles, CA, USA'} ,
  {'team_number': '12313', 'team_name': 'Hotdawgs', 'from': 'Laredo, TX, USA'} ,
  {'team_number': '12682', 'team_name': 'The Golden Ratio', 'from': 'Cary, IL, USA'} ,
  {'team_number': '13312', 'team_name': 'The Bombers', 'from': 'Saint Louis, MO, USA'} ,
  {'team_number': '14423', 'team_name': 'RoboCorns', 'from': 'Exton, PA, USA'} ,
  {'team_number': '14725', 'team_name': 'Java the Hutts', 'from': 'Fort Myers, FL, USA'} ,
  {'team_number': '15555', 'team_name': 'S.W.A.R.M.', 'from': 'Saline, MI, USA'} ,
  {'team_number': '15909', 'team_name': 'Devolt Deimos', 'from': 'Chihuahua, CHH, Mexico'} ,
  {'team_number': '16158', 'team_name': 'VC Silver Circuits', 'from': 'Virginia City, NV, USA'} ,
  {'team_number': '16460', 'team_name': 'GEarheads', 'from': 'Brookfield, WI, USA'} ,
  {'team_number': '16817', 'team_name': 'Rocksisaan Tech', 'from': 'Tonalea, AZ, USA'} ,
  {'team_number': '16818', 'team_name': 'Hype-Birds', 'from': 'Tlalpan, CMX, Mexico'} ,
  {'team_number': '17062', 'team_name': 'Techalongs', 'from': 'Scottsdale, AZ, USA'} ,
  {'team_number': '18270', 'team_name': 'RoboPlayers', 'from': 'Irving, TX, USA'} ,
  {'team_number': '18763', 'team_name': 'Texpand', 'from': 'Cape Town, WC, South Africa'} ,
  {'team_number': '19458', 'team_name': 'Equilibrium.exe', 'from': 'Potomac, MD, USA'} ,
  {'team_number': '19500', 'team_name': 'RoBEARtics', 'from': 'Scaborough, ON, Canada'} ,
  {'team_number': '19502', 'team_name': 'The Moment Makers', 'from': 'Pearland, TX, USA'} ,
  {'team_number': '19706', 'team_name': 'Potential Energy', 'from': 'Shoreview, MN, USA'} ,
  {'team_number': '19889', 'team_name': 'Robo-Sapiens', 'from': 'Wilmington, DE, USA'} ,
  {'team_number': '19953', 'team_name': 'Scrap Metal', 'from': 'Anchorage, AK, USA'} ,
  {'team_number': '20077', 'team_name': 'The Indubitables', 'from': 'Omaha, NE, USA'} ,
  {'team_number': '20131', 'team_name': 'The Inventors', 'from': 'Vari - Athens, I, Greece'} ,
  {'team_number': '20194', 'team_name': 'JackBots', 'from': 'Moorefield, WV, USA'} ,
  {'team_number': '21305', 'team_name': 'Rogue Cats', 'from': 'Duluth, MN, USA'} ,
  {'team_number': '21336', 'team_name': 'I Forgot', 'from': 'Vancouver, WA, USA'} ,
  {'team_number': '22489', 'team_name': 'Galactic Narwhal Chicken Effect - Diamond', 'from': 'Weston, MA, USA'} ,
  {'team_number': '23845', 'team_name': 'ElephantNova', 'from': 'Shanghai, SH, China'} ,
  {'team_number': '23942', 'team_name': 'BMS Rez Kidz', 'from': 'Kayenta, AZ, USA'} ,
  {'team_number': '24356', 'team_name': 'Prepa Tecmilenio WINT', 'from': 'Metepec, MEX, Mexico'} ,
  {'team_number': '24500', 'team_name': 'LITBOT', 'from': 'Kaunas, KU, Lithuania'} ,
  {'team_number': '24994', 'team_name': 'Hillel Panthers', 'from': 'Kingston , 01, Jamaica'} ,
  {'team_number': '25751', 'team_name': 'Dread Pirate Robotics', 'from': 'Huntsville, AL, USA'} ,
  {'team_number': '25865', 'team_name': 'FeNiX.exe', 'from': 'Rockville, MD, USA'} ,
  {'team_number': '26481', 'team_name': 'Atlanta Droids', 'from': 'Atlanta, GA, USA'} ,
  {'team_number': '27572', 'team_name': 'Dinonaut', 'from': 'Khon Kaen, 40, Thailand'} ,
  {'team_number': '27679', 'team_name': 'CDC Tech', 'from': 'San Juan, PR, USA'} ,
  {'team_number': '28378', 'team_name': 'Epiteugma MouflonBots 2', 'from': 'Lakatamia, 01, Cyprus'} ,
  {'team_number': '28695', 'team_name': "Ka'i", 'from': 'Maracaibo, V, Venezuela'} ,
  {'team_number': '29220', 'team_name': 'Hex', 'from': 'Jubail, 04, Saudi Arabia'}
];

List<Map<String, dynamic>> Ochoa_Division = [
  {'team_number': '3954', 'team_name': 'Pink to the Future', 'from': 'Den Haag, ZH, Netherlands'} ,
  {'team_number': '4137', 'team_name': 'IslandBots', 'from': 'East Setauket, NY, USA'} ,
  {'team_number': '4785', 'team_name': 'Anonymous Autonomous', 'from': 'Fresh Meadows, NY, USA'} ,
  {'team_number': '5485', 'team_name': 'GorillaBots', 'from': 'Corning, NY, USA'} ,
  {'team_number': '6916', 'team_name': 'ASPIRITY', 'from': 'Independent'} ,
  {'team_number': '7149', 'team_name': 'ENFORCERS', 'from': 'Egg Harbor Township, NJ, USA'} ,
  {'team_number': '7418', 'team_name': 'Batteries Not Included', 'from': 'South Burlington, VT, USA'} ,
  {'team_number': '8651', 'team_name': 'Wait For It...', 'from': 'Pearl, MS, USA'} ,
  {'team_number': '8803', 'team_name': 'East Rankin Robotics', 'from': 'Pelahatchie, MS, USA'} ,
  {'team_number': '10138', 'team_name': 'Newton Busters', 'from': 'Wilmette, IL, USA'} ,
  {'team_number': '10393', 'team_name': 'Pink Droyd', 'from': 'Brooklyn, NY, USA'} ,
  {'team_number': '10415', 'team_name': 'Warbots', 'from': 'Deerfield, IL, USA'} ,
  {'team_number': '11206', 'team_name': 'Devildogs', 'from': 'Duluth, MN, USA'} ,
  {'team_number': '11212', 'team_name': 'The Clueless', 'from': 'San Diego, CA, USA'} ,
  {'team_number': '11260', 'team_name': 'Up-A-Creek Robotics', 'from': 'Longmont, CO, USA'} ,
  {'team_number': '11444', 'team_name': 'Garnet Squadron', 'from': 'Columbia, SC, USA'} ,
  {'team_number': '14259', 'team_name': 'TURBΩ V8', 'from': 'Pleasanton, CA, USA'} ,
  {'team_number': '14481', 'team_name': "Don't Blink", 'from': 'Princeton Junction, NJ, USA'} ,
  {'team_number': '14901', 'team_name': 'Cubotics', 'from': 'New Orleans, LA, USA'} ,
  {'team_number': '16075', 'team_name': 'Crimson Crocs - Campion', 'from': 'Kingston, 02, Jamaica'} ,
  {'team_number': '16290', 'team_name': 'Z.I.P Ties', 'from': 'Sanford, FL, USA'} ,
  {'team_number': '16700', 'team_name': 'JAYBOTS', 'from': 'Hopewell Junction, NY, USA'} ,
  {'team_number': '16736', 'team_name': 'Atomic Narwhals', 'from': 'Johnston, IA, USA'} ,
  {'team_number': '16917', 'team_name': 'Gear Wizards', 'from': 'Otsego, MN, USA'} ,
  {'team_number': '17324', 'team_name': 'Green Machines', 'from': 'College Station, TX, USA'} ,
  {'team_number': '18127', 'team_name': 'All Hands on Tech', 'from': 'Lake Oswego, OR, USA'} ,
  {'team_number': '18240', 'team_name': 'RoboScout Squad', 'from': 'Kalispell, MT, USA'} ,
  {'team_number': '18397', 'team_name': 'Aztechs', 'from': 'Urbandale, IA, USA'} ,
  {'team_number': '18420', 'team_name': 'Metal Masters', 'from': 'Peoria, AZ, USA'} ,
  {'team_number': '18442', 'team_name': 'Gear Rotation', 'from': 'Sykesville, MD, USA'} ,
  {'team_number': '18483', 'team_name': 'Buckaroos', 'from': 'Muleshoe, TX, USA'} ,
  {'team_number': '18844', 'team_name': 'Pr0Teens', 'from': 'Richmond Hill, ON, Canada'} ,
  {'team_number': '19705', 'team_name': 'WXYZ', 'from': 'Beijing, BJ, China'} ,
  {'team_number': '19746', 'team_name': 'The Disruptingly Robocephalic BrainSTEM Robotics Team', 'from': 'Austin, TX, USA'} ,
  {'team_number': '19819', 'team_name': 'AstroBruins', 'from': 'Sunnyvale, CA, USA'} ,
  {'team_number': '19836', 'team_name': 'Hawk', 'from': 'Richmond Hill, ON, Canada'} ,
  {'team_number': '20092', 'team_name': 'RTF-RoboticTechFrox', 'from': 'Stuttgart , BW, Germany'} ,
  {'team_number': '20153', 'team_name': 'Silver Wolves', 'from': 'Kennett Square, PA, USA'} ,
  {'team_number': '20265', 'team_name': 'Heart of RoBots', 'from': 'Buzau, BZ, Romania'} ,
  {'team_number': '20369', 'team_name': 'EMCTEAMTECH', 'from': 'Santa Isabel, PR, USA'} ,
  {'team_number': '20870', 'team_name': 'Team Matrix', 'from': 'Mumbai, MH, India'} ,
  {'team_number': '21239', 'team_name': 'All Systems Go', 'from': 'Louisville, KY, USA'} ,
  {'team_number': '21311', 'team_name': 'Lion Robotics Gold', 'from': 'Clear Lake, IA, USA'} ,
  {'team_number': '21485', 'team_name': 'ScrapHeads', 'from': 'Holden, MO, USA'} ,
  {'team_number': '21689', 'team_name': 'Team Tesseract', 'from': 'Nashua, NH, USA'} ,
  {'team_number': '21836', 'team_name': 'ITKAN IAR', 'from': 'Raleigh, NC, USA'} ,
  {'team_number': '22029', 'team_name': 'ASAP', 'from': 'Raymond, AB, Canada'} ,
  {'team_number': '22043', 'team_name': 'UniREVsals VIOHALCO TECHNOLOGIES', 'from': 'Piraeus, I, Greece'} ,
  {'team_number': '22377', 'team_name': 'SigmaCorns', 'from': 'Durham, NC, USA'} ,
  {'team_number': '22411', 'team_name': 'Wild Squirrels', 'from': 'Casselton, ND, USA'} ,
  {'team_number': '23059', 'team_name': 'FALCONS', 'from': 'São Luís, MA, Brazil'} ,
  {'team_number': '23213', 'team_name': 'Open Source', 'from': 'Willis, TX, USA'} ,
  {'team_number': '23634', 'team_name': 'Iron Side Team', 'from': 'Benghazi, BA, Libya'} ,
  {'team_number': '23638', 'team_name': 'Firestorm', 'from': 'Acworth, GA, USA'} ,
  {'team_number': '24253', 'team_name': 'Giggle Pickles', 'from': 'Ferndale, MI, USA'} ,
  {'team_number': '24557', 'team_name': 'UNIMATE', 'from': 'Sao José, SC, Brazil'} ,
  {'team_number': '24702', 'team_name': 'Voltaris', 'from': 'Palm Harbor, FL, USA'} ,
  {'team_number': '24950', 'team_name': 'NOVATARD', 'from': 'Casablanca, CAS, Morocco'} ,
  {'team_number': '25100', 'team_name': 'MAD ENGINEERS', 'from': 'MUMBAI, MH, India'} ,
  {'team_number': '25171', 'team_name': 'RoboTakev', 'from': 'Izmir, 35, Türkiye'} ,
  {'team_number': '25620', 'team_name': 'Hexadecimal Nibble', 'from': 'Scottsdale, AZ, USA'} ,
  {'team_number': '26095', 'team_name': 'Iron Fist Team', 'from': 'Benghazi, BA, Libya'} ,
  {'team_number': '28028', 'team_name': 'Absolute Hack', 'from': 'Bayan Lepas, 07, Malaysia'} ,
  {'team_number': '28348', 'team_name': 'Ferdibot', 'from': 'ELBEUF, 76, France'}
];